### ISSUE TITLE
Pydantic 1에서 2로 버전 업그레이드 및 관련 코드 수정

### ISSUE THREAD

**Issue by mjkweon17** [kucc/library-service-server-test#71]
### Pydantic 1에서 2로 버전 업그레이드 및 관련 코드 수정

**목적**: 프로젝트의 Pydantic 종속성을 버전 1에서 버전 2로 업그레이드하여 최신 기능 및 개선 사항을 반영하고 프로젝트의 안정성을 유지하고자 합니다.

**요구 사항**:
- Pydantic 2와의 호환성 확보
- 기존 코드의 Pydantic 2와의 호환성 수정
- 기능 손실 없는 업그레이드 확인

**기능 설명**:
1. Pydantic 업그레이드: 프로젝트 종속성을 Pydantic 2로 업데이트합니다. 이를 위해 `requirements.txt` 파일 또는 종속성 관리 파일을 수정합니다.
2. 코드 호환성 확인: 기존 코드베이스에서 Pydantic 2 업그레이드로 인한 호환성 문제를 확인하고 수정합니다.
3. 테스트 실행: 변경 사항을 포함한 프로젝트를 테스트하여 모든 기능이 올바르게 작동하는지 확인합니다.
4. 문서 업데이트: Pydantic 2로의 업그레이드로 인해 모델 및 유효성 검사 사용 방법에 변경 사항이 있는 경우, 프로젝트 문서를 업데이트하여 반영합니다.

**작업 내용**:
- `requirements.txt` 파일을 수정하여 Pydantic 2로 종속성 업데이트
- 기존 코드에서 Pydantic 2와 관련된 참조 및 함수 호출 확인하고 수정
- 업데이트된 코드로 프로젝트 테스트 수행
- 변경된 사용 방법을 포함하여 프로젝트 문서 업데이트

**참고**:
- 변경 사항을 적용하기 전에 프로젝트를 백업해야 함
- 팀원들과 협력하여 업그레이드 프로세스를 조율
- 변경된 기능 및 사용 방법을 문서화하여 개발자들이 쉽게 참고 가능

**Comment by mjkweon17** [comment]
- fastapi 버전 0.101.1로 업그레이드
- pydantic 버전 2.1.1로 업그레이드
- pydantic-settings 모듈 설치

**Comment by mjkweon17** [comment]
- pydantic v1에 있었던 BaseSettings는 pydantic-settings로 이동됨
- 따라서 BaseSettings를 사용하기 위해서는 from pydantic_settings import BaseSettings를 적어줘야 함

**Comment by mjkweon17** [comment]
pydantic v2로 업그레이드했더니 아래와 같은 에러가 발생

https://github.com/aiogram/aiogram/issues/1222#issuecomment-1643177952 에 의하면 python 버전의 문제같음
현재 우리가 작업하는 파이썬 버전은 3.10.0rc2
파이썬 버전을 3.10.11로 업데이트한 후 결과를 커멘트로 추가하겠음


```
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\explo\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\explo\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\explo\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run  
    return loop.run_until_complete(main)
  File "C:\Users\explo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\uvicorn\config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
    raise exc from None
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\explo\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\explo\Desktop\library-service-server-test\app\main.py", line 4, in <module>
    from routers import users, notice, books
  File "C:\Users\explo\Desktop\library-service-server-test\app\routers\users.py", line 3, in <module>    
    from database import get_db
  File "C:\Users\explo\Desktop\library-service-server-test\app\database.py", line 4, in <module>
    from config import Settings
  File "C:\Users\explo\Desktop\library-service-server-test\app\config.py", line 20, in <module>
    from pydantic import BaseSettings
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\pydantic\__init__.py",     return _getattr_migration(attr_name)
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\pydantic\_migration.py", line 289, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.1.1/migration/#basesettings-has-moved-to-pydantic-settings for more details.       

For further information visit https://errors.pydantic.dev/2.1.1/u/import-error
INFO:     Stopping reloader process [17196]
(venv) PS C:\Users\explo\Desktop\library-service-server-test\app> uvicorn main:app --reload
INFO:     Will watch for changes in these directories: ['C:\\Users\\explo\\Desktop\\library-service-server-test\\app']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [288] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\explo\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\explo\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\explo\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run      
    return loop.run_until_complete(main)
  File "C:\Users\explo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\uvicorn\config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\explo\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\explo\Desktop\library-service-server-test\app\main.py", line 4, in <module>
    from routers import users, notice, books
  File "C:\Users\explo\Desktop\library-service-server-test\app\routers\users.py", line 3, in <module>        
    from database import get_db
  File "C:\Users\explo\Desktop\library-service-server-test\app\database.py", line 4, in <module>
    from config import Settings
  File "C:\Users\explo\Desktop\library-service-server-test\app\config.py", line 20, in <module>
    from pydantic_settings  import BaseSettings
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\pydantic_settings\__init__.py", line 1, in <module>
    from .main import BaseSettings, SettingsConfigDict
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\pydantic_settings\main.py", line 40, in <module>
    class BaseSettings(BaseModel):
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 172, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 400, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\pydantic\_internal\_fields.py", line 98, in collect_model_fields
    type_hints = get_cls_type_hints_lenient(cls, types_namespace)
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\pydantic\_internal\_typing_extra.py", line 212, in get_cls_type_hints_lenient
    hints[name] = eval_type_lenient(value, globalns, localns)
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\pydantic\_internal\_typing_extra.py", line 221, in eval_type_lenient
    value = _make_forward_ref(value, is_argument=False, is_class=True)
TypeError: ForwardRef.__init__() got an unexpected keyword argument 'is_class'
```

**Comment by mjkweon17** [comment]
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: book_id = <class 'int'> 에러 발생했고 해결 완료
자세한 내용은 #75 참고 바람

**Comment by mjkweon17** [comment]
UserWarning: Valid config keys have changed in V2: * 'orm_mode' has been renamed to 'from_attributes'
경고 발생했고 해결 완료
자세한 내용은 #76 참고 바람

**Comment by mjkweon17** [comment]
수빈이가 수정된 부분 pull 받았더니 아래와 같은 에러가 발생한다고 함.
추후 진권이도 테스트가 끝나면 원인 발견 후 에러 수정하겠음

```
from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (C:\Users\smreo\PycharmProjects\library-service-server-test\app\venv\lib\site-packages\pydantic\fields.py)
``` 

```
File "C:\Users\smreo\PycharmProjects\library-service-server-test\app\main.py", line 4, in <module>
    from routers import users, notice, books
ModuleNotFoundError: No module named 'routers'
```
