### ISSUE TITLE
에러 발생 - pydantic v2로 업그레이드한 후 TypeError 발생

### ISSUE THREAD

**Issue by mjkweon17** [kucc/library-service-server-test#74]
## 문제 설명
pydantic v2로 업그레이드하면서 아래와 같은 에러가 발생합니다:

이 문제는 pydantic_settings 라이브러리의 버전 업그레이드로 인해 발생하는 것으로 보입니다. 현재 업데이트된 버전에서는 ForwardRef.__init__() 함수에 is_class라는 예상치 못한 키워드 인자가 전달되는 문제가 있습니다.

aiogram/aiogram#1222 (comment)에 의하면, 이 문제는 파이썬 버전과 관련이 있을 수 있습니다. 
문제 해결을 위해 파이썬 버전을 3.10.0rc2에서 3.10.11로 업데이트하고 다시 시도해 보겠습니다. 문제가 해결되는지 결과를 커멘트로 공유하겠습니다.

## 에러 메시지
```
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\explo\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\explo\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\explo\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run      
    return loop.run_until_complete(main)
  File "C:\Users\explo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\uvicorn\config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\explo\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\explo\Desktop\library-service-server-test\app\main.py", line 4, in <module>
    from routers import users, notice, books
  File "C:\Users\explo\Desktop\library-service-server-test\app\routers\users.py", line 3, in <module>        
    from database import get_db
  File "C:\Users\explo\Desktop\library-service-server-test\app\database.py", line 4, in <module>
    from config import Settings
  File "C:\Users\explo\Desktop\library-service-server-test\app\config.py", line 20, in <module>
    from pydantic_settings  import BaseSettings
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\pydantic_settings\__init__.py", line 1, in <module>
    from .main import BaseSettings, SettingsConfigDict
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\pydantic_settings\main.py", line 40, in <module>
    class BaseSettings(BaseModel):
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 172, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 400, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\pydantic\_internal\_fields.py", line 98, in collect_model_fields
    type_hints = get_cls_type_hints_lenient(cls, types_namespace)
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\pydantic\_internal\_typing_extra.py", line 212, in get_cls_type_hints_lenient
    hints[name] = eval_type_lenient(value, globalns, localns)
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\pydantic\_internal\_typing_extra.py", line 221, in eval_type_lenient
    value = _make_forward_ref(value, is_argument=False, is_class=True)
TypeError: ForwardRef.__init__() got an unexpected keyword argument 'is_class'
```

**Comment by mjkweon17** [comment]
버전 업그레이드 후 해결 완료
