### ISSUE TITLE
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `book_id = <class 'int'>`

### ISSUE THREAD

**Issue by mjkweon17** [kucc/library-service-server-test#75]
## 문제 설명
pydantic v2로 업그레이드하면서 missing annotation에러가 발생합니다.

공식 문서 https://docs.pydantic.dev/dev-v2/errors/usage_errors/#model-field-missing-annotation 에 의하면 모든 model field에 type annotation을 추가하는 것으로 해결할 수 있다고 합니다.

에러 메시지에 의하면 shema.py의 HoldingID 클래스에서 bool_id 부분에 문제가 발생하고 있다고 합니다. 과정 및 결과를 comment로 공유하겠습니다.

```
C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\pydantic\_internal\_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\explo\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\explo\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\explo\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run      
    return loop.run_until_complete(main)
  File "C:\Users\explo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\uvicorn\config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\explo\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\explo\Desktop\library-service-server-test\app\main.py", line 4, in <module>
    from routers import users, notice, books
  File "C:\Users\explo\Desktop\library-service-server-test\app\routers\notice.py", line 3, in <module>       
    from internal.schemas.schema import NoticeOut, NoticeQuery, PeriodQuery, OrderBy
  File "C:\Users\explo\Desktop\library-service-server-test\app\internal\schemas\schema.py", line 81, in <module>
    class HoldingID(BaseModel):
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 98, in __new__
    private_attributes = inspect_namespace(
  File "C:\Users\explo\Desktop\library-service-server-test\app\venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 347, in inspect_namespace
    raise PydanticUserError(
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `book_id = <class 'int'>`. All model fields require a type annotation; if `book_id` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

For further information visit https://errors.pydantic.dev/2.1.1/u/model-field-missing-annotation
```

**Comment by mjkweon17** [comment]
book_id에 올바른 연산자를 사용해서 annotation을 설정해줬고, 이에 따라 문제가 해결됐습니다.

Before
```python
class HoldingID(BaseModel):
    book_id = int
    __setattr__ = object.__setattr__

    def __init__(self, num):
        self.book_id = num
``` 

After
```python
class HoldingID(BaseModel):
    book_id: int
    __setattr__ = object.__setattr__

    def __init__(self, num):
        self.book_id = num
```
